### ISSUE TITLE
Bathroom renos

### ISSUE THREAD

**Issue by andrewjamesbrown** [andrewjamesbrown/renovations#1]
- [ ] finish trim
- [ ] paint touch ups 
- [ ] paint trim
- [ ] finish tiling
- [ ] grout shower tiles
- [ ] install light fixtures, outlets, switches
- [ ] install toilets, sink faucets, and bath/shower fixtures
- [ ] install heated towel rail
- [ ] install glass (mirrors, shower/bath glass)
- [ ] install vanity lights
- [ ] air seal fixtures in attic (spray foam)
- [ ] interior trim side door
- [ ] exterior brickmould side door
- [ ] install front door
- [ ] install front door interior trim
- [ ] install front door exterior trim
- [ ] stain front door interior wood
- [ ] install white window hardware and return copper hardware to Strassburger
- [ ] install screens for new windows
- [ ] repair garage door aluminum capping
- [ ] paint repair wall by bathrooms
- [ ] paint repair wall beside stairs
- [ ] repair exterior wall in guest bedroom below window
- [ ] hang extra wiring to attic rafter
- [ ] re-attach bathroom fan insulation to underside of roof
- [ ] attic insulation

**Comment by poliva83** [comment]
Are you planning on writing code to accomplish all these tasks? If so I am willing to help out with the test specs.

**Comment by andrewjamesbrown** [comment]
@poliva83 you make me laugh 😸
